# Generated by Django 2.2.3 on 2022-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20220629_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicado_comentario',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
