# Generated by Django 2.2.3 on 2022-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_cat',
            field=models.CharField(max_length=30, verbose_name='Nome categoria'),
        ),
    ]
